### ISSUE TITLE
openai-api key exposed 

### ISSUE THREAD

**Issue by KartikeyMish** [GeekyJashan/mercorChallenge#1]
In `other.py` file you have exposed your API key  & it can be used by others.

Also for managing all the API keys and Secret codes you can create `.env` file for your project locally and then can get them into your project files by using os.getenv() method - used to retrieve the environment environment variable.

For example:

1. create `.env` file and put your api key  
``` .env[ ]
// dummy api key for example
OPEN_AI_API = sk-1223345567889866544234
```

2. Where ever u wanna use it like `main.py` , use os.getenv()
``` python[]
import os 
import openai

openai.api_key = os.getenv("OPEN_AI_API")
```

**Comment by GeekyJashan** [comment]
Thanks for telling,
Actually that key was already distinct, thats why I didnot hide it.
Also I did use env file to get that key but something went wrong in the end
and I simply hard coded the key.

Anyways,I wanted to have a talk with you regarding your interview
experience, could you please come on discord and we could have a 2 minute
chat about it.

Regards
Jashan

**Comment by KartikeyMish** [comment]
check discord
